@startuml HU01 - Administrador registra empleado

actor navegador
boundary employee.routes
boundary "React (employeeForm.jsx)" as ReactView
control employee.controller
entity employee
entity logs
database PostgreSQL

autonumber

navegador -> employee.routes : GET /employee/add
activate employee.routes

employee.routes -> employee.controller: getAdd(request, response)
deactivate employee.routes
activate employee.controller

employee.controller -> ReactView: response.send(App React)
deactivate employee.controller
activate ReactView

ReactView -> navegador : Mostrar formulario para agregar empleado
activate navegador

navegador -> ReactView : Ingresa datos obligatorios\n(house_id, role_id, name, surname, email, curp)

alt Ingresar datos opcionales
    navegador -> ReactView : Ingresa datos opcionales\n(rfc, nss, bank_account, birth_date, picture)
else No
    ReactView -> ReactView : Continúa sin opcionales
end

ReactView -> ReactView : Validar campos obligatorios

alt Campos incompletos
    ReactView -> navegador : Mostrar error "Campos obligatorios faltantes"
    deactivate ReactView
else Campos completos

    navegador -> employee.routes : POST /employee
    deactivate navegador
    activate employee.routes

    employee.routes -> employee.controller : postAdd(request, response)
    deactivate employee.routes
    activate employee.controller

    employee.controller -> PostgreSQL : SELECT * FROM employee WHERE curp = ?
    activate PostgreSQL
    PostgreSQL -->> employee.controller : Resultado
    deactivate PostgreSQL

    alt Usuario ya existe
        employee.controller -> ReactView : alert("Usuario ya existente")
        activate ReactView

        ReactView -> employee.routes : response.redirect("/employee/{employee_id}")
        deactivate ReactView
        
    else Usuario no existe
        
        create employee
        employee.controller -> employee : create({\n employee_id,\n house_id,\n role_id,\n name,\n surname,\n is_active,\n email,\n password,\n has_first_login,\n totp_secret,\n curp,\n rfc,\n nss,\n bank_account,\n birth_date,\n picture,\n start_date\n})
        activate employee

        employee.controller ->> employee : create()
        
        employee ->> PostgreSQL : INSERT INTO employee(\nemployee_id,\nhouse_id,\nrole_id,\nname,\nsurname,\nis_active,\nemail,\npassword,\nhas_first_login,\ntotp_secret,\ncurp,\nrfc,\nnss,\nbank_account,\nbirth_date,\npicture,\nstartd_ate)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

        activate PostgreSQL
        PostgreSQL -->> employee : Insert OK
        deactivate PostgreSQL

        employee -->> employee.controller : Promesa
        deactivate employee

        create logs
        employee.controller -> logs : create({ log_id, employee_id, moment, action_id, affected, ip_address })
        activate logs

        logs -> PostgreSQL : INSERT INTO logs(\nlog_id,\nemployee_id,\nmoment, \naction_id, \naffected, \nip_address)\nVALUES (?, ?, ?, ?)
        activate PostgreSQL
        PostgreSQL -->> logs : Insert OK
        deactivate PostgreSQL

        logs -->> employee.controller : Promesa
        deactivate logs
        
        employee.controller -> ReactView : alert("Usuario creado con éxito")
        deactivate employee.controller
        activate ReactView
        
        ReactView -> employee.routes : response.redirect("/employee/{employee_id}")
        deactivate ReactView

    end
end

@enduml