@startuml
title US48 - Consultar eventos personales en el calendario (Sequence Diagram)

actor Empleado
boundary "event.route.js\nrouter" as Router
control "Middlewares\nRateLimit, Auth, RBAC, ABAC" as Middlewares
control "get.controller.js\ngetEventsInRange()" as Controller
control "get.service.js\ngetEventsInRange()" as Service
control "utils/dates.js" as DatesUtil
entity "employee/get.model.js" as EmployeeModel
entity "event/get.model.js" as EventModel
entity "absence/get.model.js" as AbsModel
control "utils/mappers\nabsence.map.js / event.map.js" as Mappers
database "BD (Prisma)" as BD

activate Empleado
Empleado -> Router : GET /range/:id/:startDate/:endDate
deactivate Empleado
activate Router
Router -> Middlewares : apiLimiter, verifyToken,\nrequireRole, requirePrivileges, isAllowed
deactivate Router
activate Middlewares
Middlewares --> Router : next()
deactivate Middlewares

activate Router
Router -> Controller : getEventsInRange(req, res)
deactivate Router
activate Controller

Controller ->> Service : await getEventsInRange(employeeId, startDate, endDate)
activate Service

Service -> Service : dateRangeSchema.safeParse({ startDate, endDate })
Service -> DatesUtil : stringToDate(rawStartDate/EndDate)
activate DatesUtil
DatesUtil -->> Service: parsedDate
deactivate DatesUtil
Service ->> EmployeeModel : await findById(employeeId)
activate EmployeeModel
EmployeeModel ->> BD : prisma.employee.findUnique(...)
activate BD
BD -->> EmployeeModel : employee/null
deactivate BD
EmployeeModel -->> Service : employee

alt employee === null
    Service --> Controller : { code: RESPONSES.EMPLOYEE.NOT_FOUND }
    Controller -> Router: res.status(404).json({message: "Empleado no encontrado"})
    activate Router
    Router -> Empleado: res.status(404).json({message: "Empleado no encontrado"})
    deactivate Router
else Empleado existe
    Service ->> EventModel : await getPersonalEventsInRange(employeeId, startDate, endDate)
    activate EventModel
    EventModel ->> BD : prisma.personal_event.findMany(...)
    activate BD
    BD -->> EventModel : personalEvents
    deactivate BD
    EventModel -->> Service : personalEvents
    deactivate EventModel
    loop por cada evento personal
        Service -> Mappers : mapPersonalCalendarEvent(event)
        activate Mappers

        alt event.trainer === null
            Mappers -> Mappers : trainer = null
        else event.trainer !== null
            Mappers -> Mappers : trainer = event.trainer
        end
        
        Mappers -->> Service : evento personal mapeado
        deactivate Mappers
        Service -> Service : events.push(...)
    end
    Service -->> Controller : { code: RESPONSES.EVENTS.FOUND, data: { events } }
end
deactivate Service

Controller -> Router : res.status(200).json(data)
deactivate Controller
activate Router
Router -> Empleado: res.status(200).json(data)
deactivate Router

@enduml
