@startuml HU - Registro de evento personal

|Coordinador/Empleado|
start
:Interactuar con el calendario;

|Sistema|
:Renderizar modal de creación;

|Coordinador/Empleado|
:Seleccionar opción "Personal";
repeat
:Llenar campos obligatorios:
- Título
- Tipo de evento
- Fecha
- Hora inicio
- Hora de fin
- Seleccionar empleado(s);

|Sistema|
if (¿Activar "Todo el día"?) then (SI)
    :Eliminar selectores de hora;
    :Registrar solo fecha;
else (NO)
    :Mantener selectores de hora;
endif

if (¿Ingresar descripción?) then (SI)
    |Coordinador/Empleado|
    :Ingresar descripción del evento;
else (NO)
endif

|Sistema|
repeat while (¿Los campos obligatorios están completos?) is (NO)
:Validar disponibilidad de horario;

if (¿Existe empalme con otro evento?) then (SI)
    |Coordinador/Empleado|
    if (¿Desea agregar el evento de todos modos?) then (SI)
        |Sistema|
        :Registrar evento con traslape;
    else (NO)
        |Sistema|
        :Cancelar operación;
        stop
    endif
else (NO)
    |Sistema|
    :Registrar evento normalmente;
endif

|Sistema|
:Notificar éxito al usuario;
:Actualizar calendario;
stop

@enduml