@startuml

|Usuario|
start
:Ingresa a la página de vacaciones;

|Sistema|
:Obtiene vacaciones futuras;
:Obtiene vacaciones pasadas;
:Muestra las vacaciones en listas separadas;

if (¿Se consultan vacaciones futuras?) then (Sí)
:Muestra las vacaciones más cercanas primero;
else (No)
:Muestra las vacaciones pasadas\nmás recientes primero;
endif

:Muestra únicamente el máximo de vacaciones\npermitidas por página;

|Usuario|
:Selecciona filtros de estado\no rango de fechas;

|Sistema|
:Obtiene vacaciones con los filtros seleccionados;

if (¿Hay vacaciones que coincidan?) then (Sí)
:Renderiza las vacaciones filtradas;
else (No)
:Muestra que no hay vacaciones para mostrar;
endif

if (¿Vacación es pasada?) then (Sí)
:Muestra únicamente el botón de ver detalle;
else (No)
    :Muestra botón de ver detalle y eliminar;
    if (¿Vacación está pendiente?) then (Sí)
    :Añade botón de editar;
    endif
endif

|Usuario|
:Presiona botón de ver detalle;

|Sistema|
:Redirecciona al calendario;
:Mueve el calendario al mes de la vacación;
:Obtiene la vacación seleccionada;
:Renderiza el detalle de la vacación;

stop
@enduml
