const VACATION_STATUS = {
    PENDING: 0,
    APPROVED: 1,
    REJECTED: 2,
};

const ACTIVE_VACATION_STATUSES = [
    VACATION_STATUS.PENDING,
    VACATION_STATUS.APPROVED,
];

module.exports = {
    VACATION_STATUS,
    ACTIVE_VACATION_STATUSES,
};